name: Fortnite Shop to Discord (Daily at 6 AM ET)
on:
  # Runs at 10:00 UTC, which is 6:00 AM ET
  workflow_dispatch:      # Allows manual triggering from GitHub
jobs:
  post_shop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Run shop bot
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          FORTNITE_API_KEY: ${{ secrets.FORTNITE_API_KEY }}
        run: python shop_bot.py
